### ISSUE TITLE
[bug] not working include post data when use `--include-burp` flag

### ISSUE THREAD

**Issue by hahwul** [hahwul/authz0#10]
https://github.com/hahwul/authz0/blob/main/pkg/new/new.go#L132

**Comment by hahwul** [comment]
https://pkg.go.dev/net/http#Request

**Comment by hahwul** [comment]
Body [io](https://pkg.go.dev/io).[ReadCloser](https://pkg.go.dev/io#ReadCloser)

**Comment by hahwul** [comment]
## Test
```
$ authz0 new 444 --include-zap 111.har
Mar  4 00:17:57.749 [INFO] import HAR(ZAP) file
Mar  4 00:17:57.750 [INFO] [444] generate template
```

```yaml
name: ""
roles: []
urls:
- url: https://www.hahwul.com/
  method: POST
  contentType: ""
  body: '{"1": "2"}'
  allowRole: []
  denyRole: []
  alias: ""
- url: https://www.hahwul.com/
  method: POST
  contentType: ""
  body: 1=2
  allowRole: []
  denyRole: []
  alias: ""
asserts: []
credentials: []
```
